/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
package org.hibernate.dialect.identity;

import org.hibernate.MappingException;

/**
 * Identity column support implementation for SAP HANA database.
 * <p>
 * This class provides SAP HANA-specific support for identity/auto-increment
 * columns. It extends {@link IdentityColumnSupportImpl} to handle HANA's
 * identity column functionality.
 * <p>
 * HANA identity column characteristics:
 * <ul>
 *   <li>Supports identity columns with "GENERATED BY DEFAULT AS IDENTITY" syntax</li>
 *   <li>Uses current_identity_value() function to retrieve last generated value</li>
 *   <li>Implicitly starts with 1 and increments by 1</li>
 *   <li>Provides full identity column support</li>
 * </ul>
 * <p>
 * SAP HANA provides comprehensive and standards-compliant identity column support.
 *
 * @see IdentityColumnSupport
 * @see IdentityColumnSupportImpl
 * @see HANADialect
 *
 * @author Hibernate Team
 */
public class HANAIdentityColumnSupport extends IdentityColumnSupportImpl {

	public static final HANAIdentityColumnSupport INSTANCE = new HANAIdentityColumnSupport();

	@Override
	public boolean supportsIdentityColumns() {
		return true;
	}

	@Override
	public String getIdentitySelectString(String table, String column, int type) throws MappingException {
		return "select current_identity_value() from " + table;
	}

	@Override
	public String getIdentityColumnString(int type) {
		// implicitly start with 1 increment by 1
		return "generated by default as identity";
	}

}
